### ISSUE TITLE
Dependent Option Set Manager

### ISSUE THREAD

**Issue by PreetamYengkokpam** [GuidoPreite/DOSM#1]
Hello Guido,
Thanks so much for providing the solution to create dependent OptionSet on Dynamics 365 forms. I have been using the solution for implementations.
I downloaded the latest version (Dependent Option Set Manager 1.0.0.0). Now I am trying to create dependency on 3 levels of option set. I tried but when I added the 3rd option set, it stopped working,

Kindly let me know if 3 levels of option set dependency will work using your solution?

Thank you,
Preetam

**Comment by GuidoPreite** [comment]
Hi Preetam,
DOSM should work on 3 levels, if you can share the configuration (with screenshots and the json generated) I can try to assist to resolve your issue.

**Comment by GuidoPreite** [comment]
Hi @PreetamYengkokpam, I close this issue as I don't know if you resolved your problem. If you still having problems you can contact me directly or ask again here. Thanks.
