### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by MANEnterprise-Joseph** [GuidoPreite/DOSM#10]
Hello, I'm sorry for asking such a trivial question, but this is the first time I'm starting to use the Dependent Option Set Manager. How can I integrate it with my CRM? Is there a documentation on getting started? 

I downloaded https://github.com/GuidoPreite/DOSM/releases/download/1.0.0.3/DependentOptionSetManager_1_0_0_3_managed.zip
so how can I go from here?

**Comment by GuidoPreite** [comment]
Hi @MANEnterprise-Joseph,
you are right, there isn't a documentation on how to start.
The file you downloaded is a Dynamics 365 solution, you need to install first, you need to go to https://make.powerapps.com/, there you select the environment, click on the "Solutions" in the left menu and from there you see a button to import the solution.
After the solution is imported you go to the Apps selection (by clicking on the current app name or by going to the url 
myurl.crm[number].dynamics.com/main.aspx?forceUCI=1&pagetype=apps

there you will see the DOSM app and it will be the same as the demo.
Let me know if this solve your issue.
