### ISSUE TITLE
Yes/No (boolean) choices aren't shown

### ISSUE THREAD

**Issue by malarky213** [GuidoPreite/DOSM#12]
Testing this out, and I noticed that you can't select boolean choice fields as the parent.  I tried to manually make it happen and I get this error:
 TypeError: Cannot read properties of undefined (reading 'indexOf')
    at .../webresources/gp_/js/dosm_DependentOptionSet.js:70:49
    at Array.forEach (<anonymous>)
    at .../webresources/gp_/js/dosm_DependentOptionSet.js:70:16
    at Array.forEach (<anonymous>)
    at DOSM.Utilities.GetUniqueEntriesFromArrays (.../webresources/gp_/js/dosm_DependentOptionSet.js:68:15)
    at ...//webresources/gp_/js/dosm_DependentOptionSet.js:280:52
    at Array.forEach (<anonymous>)
    at DOSM.FilterField (.../webresources/gp_/js/dosm_DependentOptionSet.js:249:32)
    at b._executeFunctionInternal (https://content.powerapps.com/resource/uci-infra/scripts/app.e64ad7545da1714be43e5aa5ff60575b.js:14:1246891)
    at b.execute (https://content.powerapps.com/resource/uci-infra/scripts/app.e64ad7545da1714be43e5aa5ff60575b.js:14:1245325)

Error Details:
Event Name: onchange
Function Name: DOSM.FilterField
Web Resource Name: gp_/js/dosm_DependentOptionSet.js
Solution Name: DependentOptionSetManager
Publisher Name: guidopreite

Looks like its specifically this line (265) that it bombs out on: 
_if (Array.isArray(otherParentFieldValue)) {_

I was thinking about trying to update dosm_DependentOptionSet.js to make it skip this if the field is boolean, but I thought I would see if there were any other workarounds before I go making edits.

**Comment by GuidoPreite** [comment]
Hi @malarky213 , you cannot select Boolean fields as the script only consider OptionSet/Choice fields.
This is the reason you are getting an error.
You can make changes as you wish, keep in mind that the solution deployment is managed.
Let me know if you have other questions.

**Comment by malarky213** [comment]
Thanks for the quick response @GuidoPreite!

One follow up question - do you know off hand what privileges are needed to make updates to the webresource files and form fields?  Could I give this to a subset of users who are not System Admins to make updates?

**Comment by GuidoPreite** [comment]
@malarky213 System Administrator or System Customizer, both roles have a very big impact on customizations (there isn't a role only for Web Resources)

**Comment by venjirai** [comment]
> Hi @malarky213 , you cannot select Boolean fields as the script only consider OptionSet/Choice fields. This is the reason you are getting an error. You can make changes as you wish, keep in mind that the solution deployment is managed. Let me know if you have other questions.

Hey, any hope you will consider adding support for Yes/No fields in a future release or aren't you releasing any new updates for this library?

**Comment by GuidoPreite** [comment]
@venjirai right now no plans to make a new release to add boolean fields.
