### ISSUE TITLE
Item options read only

### ISSUE THREAD

**Issue by venjirai** [GuidoPreite/DOSM#14]
Hey,
this is a really cool solution. In my view there is only one feature missing to make it perfect:

When adding a dependency and selecting the items it would be nice to have the option to allow some/all items in the selection to be read only. Meaning the field can't be manually set to that option but already present options should not be deleted when opening the form.

Example:
I have a custom invoice entity with a status option set:
- Open
- Paid
- Void
- ... and some more

To void an invoice one must always press a custom "Void invoice" command.
I don't want the option for the user to manually change the status to "Void".
Now if the user voids the invoice with the command, the system does some checks and then sets the status to "Void".
If I use your solution and only allow "Open" and "Paid" (for a parent field I didn't mention) and the user opens the form for a void invoice, it will clear the status.

Ideally, I use your solution and when adding the "Void" option I also define it "read-only", so when opening an invoice which is in another status than "Void", it won't show the "Void" option but when opening a voided invoice it also doesn't delete the "Void" option either.

**Comment by GuidoPreite** [comment]
Hi @venjirai, as far as I remember (I may be wrong) there isn't a way for a OOB optionset control to make some of the options not clickable and for your example (hide or show the "Void" option) it should act like a "show only if already selected". However I don't plan to add such configuration.
For your requirement I suggest to create additional javascript code (that will run after the javascript methods added by my solution to the form) to handle the "void" option.
Let me know.
Thanks
