### ISSUE TITLE
Error importing solution

### ISSUE THREAD

**Issue by SkydivinGirl** [GuidoPreite/DOSM#2]
This is really great!  I would like to try it out but I'm getting an error when attempting to import the solution.  The error is:

The element 'AppModule' has invalid child element 'OptimizedFor'. List of possible elements expected: 'WelcomePageId, FormFactor'.

We are using Dynamics 365 Version 1612 (9.0.9.4) on-Premise.

Thanks!

Heather

**Comment by GuidoPreite** [comment]
Hi @SkydivinGirl , I added a new release (1.0.0.1) that should fix the installation for On-Premise. If you can test if it works for you and let me know. Thanks

**Comment by SkydivinGirl** [comment]
This version imported perfectly!  I'll let you know if I run into any other issues.  Thank you!
