### ISSUE TITLE
Unable to edit configurations

### ISSUE THREAD

**Issue by SkydivinGirl** [GuidoPreite/DOSM#3]
Hi Guido,

I was able to create a JSON Web Resource and apply it to a form without issue.  The form seems to be updating properly.  However, when I attempt to edit the configuration, I select my solution but it does not find the web resource in the solution.  I've opened my solution and verified that the web resource is in it.  We are on-premise.

Thank you,

Heather Kent

**Comment by GuidoPreite** [comment]
Hi @SkydivinGirl , DOSM allows only to edit configurations inside the unmanaged layer, any chance that the instance you are editing the configuration is not the same where you created first the JSON Web Resource? this can be a case if the solution containing the JSON Web Resource has been moved as managed to another instance.
In order to help you I will need more details, first make sure you can show this configuration inside DOSM, ideally I will need details of the JSON used (there is a Show JSON button inside the Show Configuration part) and some screenshots on how the Edit Configuration looks like to your configuration. If you can't send these info here because it's public, you can send them to me by LinkedIn or by email (firstname.lastname gmail)

**Comment by SkydivinGirl** [comment]
Hi Guido.  Thanks for the quick responses.  The instance where I trying to edit the configuration is the same where I created the configuration and the JSON Web Resource has not been moved.  The solution I have selected is unmanaged.  I will email the screenshots you requested.

I can show the configuration of the form.  Here is the JSON:

`Dependent Option Set Manager 1.0.0.1 
Created by Guido Preite Twitter - LinkedIn - Blog 

Menu Show Notice 

Show Configuration
Configured Forms
Information (Main) Configuration: mai_dosmequipment 

DOSM Equipment Option Set Management (mai_dosmequipment)
Model Option List 1 (Sort: Default)
Select Model Option List 1 
Model Option List 2 (Sort: Default)
Select Model Option List 1 first 

Model Option List 1 (Sort: Default)
Select Model Option List 1 
Model Option List 3 (Sort: Default)
Select Model Option List 1 first 

Model Option List 1 (Sort: Default)
Select Model Option List 1 
Model Option List 4 (Sort: Default)
Select Model Option List 1 first 

Model Option List 1 (Sort: Default)
Select Model Option List 1 
Model Option List 5 (Sort: Default)
Select Model Option List 1 first 

Show JSON

JSON mai_dosmequipment
×
[
  {
    "parent": "mai_modelol1",
    "child": "mai_modelol2",
    "parent_sort": "default",
    "child_sort": "default",
    "options": {
      "809870000": [],
      "809870001": [
        "809870000",
        "809870001"
      ],
      "809870002": [],
      "809870003": [],
      "809870004": [],
      "809870005": [],
      "809870006": [],
      "809870007": [],
      "809870008": [],
      "809870009": [],
      "809870010": [],
      "809870011": [],
      "809870012": [],
      "809870013": [
        "809870000",
        "809870001"
      ],
      "809870014": [],
      "809870015": [
        "809870000",
        "809870001"
      ]
    }
  },
  {
    "parent": "mai_modelol1",
    "child": "mai_modelol3",
    "parent_sort": "default",
    "child_sort": "default",
    "options": {
      "809870000": [],
      "809870001": [
        "809870000",
        "809870001",
        "809870002"
      ],
      "809870002": [],
      "809870003": [],
      "809870004": [],
      "809870005": [],
      "809870006": [],
      "809870007": [],
      "809870008": [],
      "809870009": [],
      "809870010": [],
      "809870011": [],
      "809870012": [],
      "809870013": [
        "809870000",
        "809870001",
        "809870002"
      ],
      "809870014": [],
      "809870015": [
        "809870000",
        "809870001",
        "809870002"
      ]
    }
  },
  {
    "parent": "mai_modelol1",
    "child": "mai_modelol4",
    "parent_sort": "default",
    "child_sort": "default",
    "options": {
      "809870000": [],
      "809870001": [
        "809870002"
      ],
      "809870002": [],
      "809870003": [],
      "809870004": [],
      "809870005": [],
      "809870006": [],
      "809870007": [],
      "809870008": [],
      "809870009": [],
      "809870010": [],
      "809870011": [],
      "809870012": [],
      "809870013": [
        "809870000"
      ],
      "809870014": [],
      "809870015": [
        "809870001"
      ]
    }
  },
  {
    "parent": "mai_modelol1",
    "child": "mai_modelol5",
    "parent_sort": "default",
    "child_sort": "default",
    "options": {
      "809870000": [],
      "809870001": [
        "809870003"
      ],
      "809870002": [],
      "809870003": [],
      "809870004": [],
      "809870005": [],
      "809870006": [],
      "809870007": [],
      "809870008": [],
      "809870009": [],
      "809870010": [],
      "809870011": [],
      "809870012": [],
      "809870013": [
        "809870000",
        "809870001",
        "809870002"
      ],
      "809870014": [],
      "809870015": [
        "809870000",
        "809870001",
        "809870002"
      ]
    }
  }
]
OK
`

**Comment by GuidoPreite** [comment]
thanks for the JSON, I also received the screenshots by email

**Comment by GuidoPreite** [comment]
A new release has been published (1.0.0.2) to fix the bug regarding JSON Web Resources described in this issue. Thanks again @SkydivinGirl for providing the info for troubleshooting.
