### ISSUE TITLE
Dependent option set value is not updated even though correct option text is displayed after changing the master option set

### ISSUE THREAD

**Issue by MathewOnline** [GuidoPreite/DOSM#4]
When changing the Master option set, the first option in the dependent drop down is shown. But if we save the record at this point. The old value (Before option set change) retained in the dependent option set. So I think when we change the master option set default value of --Select--  should be displayed rather than the first item in the dependent option set.

**Comment by GuidoPreite** [comment]
Hi @MathewOnline, just to be sure if you can answer to some questions:
1) this is happening inside your form correct? how many levels you have? a single parent-child (2 levels) or a chain longer than 2 levels?
2) this is happening with normal option sets or you have multi-select option sets in your configuration?

If I understood correctly, what's happening is that when you save the record the child field is not updated with the new value (also if it's the one automatically selected)?

if you can add some screenshots they will be useful, thanks

**Comment by MathewOnline** [comment]
1) Yes this is happening in my form. I have a simple single parent child relationship (One mater option set and a child option set)
2) Normal optionset.
This happens only during update of previous value. ie on record creation and first save everything works as expected. But if you decide to go back to record and change the master option set this is where the problem exists.

**Comment by GuidoPreite** [comment]
hi @MathewOnline, I tried to replicate your issue on my test instance but it doesn't happen to me. Every time I change the parent (record already exists) the child switch to --Select-- (if you see this means you are using Unified Interface, however I tested also classic) and if the record is saved with or without a selection inside the child, both parent and child are saved correctly. The only way to assist you if you can do a short video on the error you are experiencing, also make sure that no other javascript or business rules are registered against your child field that can cause the problem you are facing.

**Comment by MathewOnline** [comment]
Sure I will record a video and send it to you. Do you have an email address where I can send it to.

**Comment by GuidoPreite** [comment]
@MathewOnline email is firstname.lastname gmail (fill with my info), you can also add me on LinkedIn

**Comment by GuidoPreite** [comment]
looks like the behavior happens when the script runs on an existing record containing data not valid for the current configuration. However I am not able to replicate the issue locally. I close this issue, in case of updates you can contact me directly
