### ISSUE TITLE
edit configuration - no new optionsets shown

### ISSUE THREAD

**Issue by Breitenkamp-DK** [GuidoPreite/DOSM#5]
Hi Guido,
I am editing my configuration after having setup s number of new option sets, however none of the new fields are available in DOSM.
What am I doing wrong?

**Comment by GuidoPreite** [comment]
Hi @Breitenkamp-DK , make sure you publish your customizations and after close and reopen again DOSM. If after these two steps you still not able to see the new fields, let me know and see how we can debug this issue.

**Comment by Breitenkamp-DK** [comment]
went: 
- Publish all Customizations
- Closed everything
- opened CRM and your app again
still no new fields...

**Comment by GuidoPreite** [comment]
Hi @Breitenkamp-DK , I think I need to see directly the behavior inside your instance. Contact me by LinkedIn or by email (firstname.lastname gmail). Thanks

**Comment by GuidoPreite** [comment]
issue is now resolved. Problem was that the specific configuration was attached to two forms and the new optionset field was only present inside one, DOSM only shows fields available in all the configured forms when editing an existing configuration.
