### ISSUE TITLE
D365 for Mobile - Android offline - TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by kolyapnl** [GuidoPreite/DOSM#6]
I get an error related to the mentioned below piece of code from JS “DependentOptionSet.js”

It is happening only offline in Android hence Classification filtration is not working. I do not see this error in iPhone offline.

Code:

DO.DependentOptionSet.filterDependentField = function (parentFieldParam, childFieldParam) {
    //Looping through the array of all the possible dependency configurations
    for (var i = 0; i < DO.DependentOptionSet.config.length; i++) {
        var dependentOptionSet = DO.DependentOptionSet.config[i];
        /* Match the parameters to the correct dependent optionset mapping*/
        if ((dependentOptionSet.parent == parentFieldParam) &&
            (dependentOptionSet.child == childFieldParam)) {
            /*
            * Using setTimeout to allow a little time between calling this potentially recursive function.
            * Without including some time between calls, the value at the end of the chain of dependencies 
            * was being set to null on form load.
            */
            var fieldConfiguration = JSON.parse(JSON.stringify(dependentOptionSet)); // just make sure we pass by value and not by ref
            setTimeout(DO.DependentOptionSet.filterOptions, 100, parentFieldParam, childFieldParam, fieldConfiguration);
        }
    }
};

Error:

TypeError: Cannot read property 'length' of null 
    at Object.DO.DependentOptionSet.filterDependentField (<anonymous>:72:54) 
    at _executeFunctionInternal (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:1861:4436) 
    at _.execute (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:1861:3648) 
    at https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:125:22713 
    at i (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:278:88) 
    at X._executeIndividualEvent (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:125:22687) 
    at X._executeEventHandler (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:125:19552) 
    at Object.execute (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:125:18943) 
    at j._executeSyncAction (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:828:692) 
    at j._executeSync (https://crm-dev.crm11.dynamics.com/uclient/scripts/app.js?v=1.4.2635-2105.1:828:419) 
Error Details: 
Event Name: onchange 
Function Name: DO.DependentOptionSet.filterDependentField 
Web Resource Name: gp_/js/DependentOptionSet.js 
Solution Name: DependentOptionSetGenerator 
Publisher Name: guidopreite

Please check this - https://community.dynamics.com/crm/f/microsoft-dynamics-crm-forum/239651/error-in-dependent-option-set/850261

SDK.DependentOptionSet.completeInitialization = function () { 
    for (var i = 0; i < SDK.DependentOptionSet.config.length; i++) { 
              var parentControl = Xrm.Page.getControl(SDK.DependentOptionSet.config[i].parent);
              var childControl = Xrm.Page.getControl(SDK.DependentOptionSet.config[i].child);
              if (parentControl != null && childControl != null) {
                    var parentAttribute = Xrm.Page.getAttribute(SDK.DependentOptionSet.config[i].parent);
                    var parentFieldValue = parentAttribute.getValue();
                    if (parentFieldValue == null || parentFieldValue == -1) { 
                           var childAttribute = Xrm.Page.getAttribute(SDK.DependentOptionSet.config[i].child); 
                           childAttribute.setValue(null); 
                           childAttribute.controls.forEach(function (c) { c.setDisabled(true); }); 
                    } 
                    else { 
                           parentAttribute.fireOnChange(); 
                    } 
              }
    } 
}

**Comment by GuidoPreite** [comment]
Looks like you are getting the error on the previous version (the Generator) and not the new solution (Dependent Option Set Manager - DOSM). You can try to upgrade your existing configuration and see if with the new script the offline problem with Android you are facing is resolved (please try this inside a sandbox/test instance first). Let me know if you need guidance or something else. Thanks
