### ISSUE TITLE
Show Configuration Error - Error retrieving required data.

### ISSUE THREAD

**Issue by kolyapnl** [GuidoPreite/DOSM#7]
We have had an old version of DO solution DependentOptionSetGenerator 1.0.0.2.
We have installed new version of DOSM solution DependentOptionSetManager 1.0.0.2

After installation we went to the App and Clicked "Upgrade from Dependent OptionSet Generator". The upgrade happened successfully (with no errors).

after all, we checked "Show Configuration" and we can see all our "Configured Forms" listed in the drop-down
 
But when we click on the one of the option we see the error.
![image](https://user-images.githubusercontent.com/84792636/120389126-ac380400-c334-11eb-9cab-bbe312cb9451.png)

![Screenshot 2021-06-01 155524](https://user-images.githubusercontent.com/84792636/120389500-2a94a600-c335-11eb-86c5-d31a497402b0.jpg)

**Comment by GuidoPreite** [comment]
Thanks for the screenshots. I quickly checked the error you received and looks like the script is not able to retrieve the entity where the script is attached (or the web resource containing the json, but I see it has been loaded inside your second screenshot). I can start to check this issue better during the weekend, if you can contact me by email is better. I keep this issue open and I close the other one you opened.

**Comment by kolyapnl** [comment]
Thanks for your quick reply! May I know your email?
About ticket/issue #6 please do not close it since we cannot test it because we cannot upgrade Generator to Manager yet.

**Comment by GuidoPreite** [comment]
email is firstname.lastname gmail (fill with my info), you can also add me on LinkedIn

**Comment by GuidoPreite** [comment]
This specific issue was connected to the upgrade of the previous Generator solution. The Web Resource was referenced inside the script with a "/" at the beginning (like "/sample_/sample_nba_config.js") but the Web Resource needs to be referenced without a "/" at beginning ("sample_/sample_nba_config.js"). Thanks @kolyapnl for noticing it. After the parameter for DOSM.LoadConfiguration has been corrected, DOSM was able to show the configuration. This ticket is now closed
