### ISSUE TITLE
Form is not visible when editing a new configuration, but it shows correctly in Show Entities and Form Fields

### ISSUE THREAD

**Issue by alexeisenhart** [GuidoPreite/DOSM#9]
First off, I love this tool!

I'm trying to configure a new web resource. I can see the form listed in Show Entities and Form Fields --

![image](https://user-images.githubusercontent.com/72568950/214365194-9d408654-4c13-4154-b910-47c335df1f23.png)

But the same entity doesn't allow me to select a form when in Edit Configuration. I DO have the option sets added to the Information form. I've tried switching my option sets to Global or Local.... but no change. I have another entity in this solution which has no options on the form, and that form is available in Edit Configuration (but obviously without any options to configure)

![image](https://user-images.githubusercontent.com/72568950/214365285-db0ed4b6-4f77-482e-aaeb-3f770d018c6e.png)

What might cause this table to not show up in Edit Configuration?

**Comment by GuidoPreite** [comment]
it's a strange issue because I use the same function inside the code in both points, no idea why it happens in your system.
If you open the developer tools of your browser and see the network, you should see the call to "systemforms" endpoint in both cases, that maybe will give more insights to what is happening in your system.

**Comment by alexeisenhart** [comment]
Interesting... this GET request https://xxx.crm.dynamics.com/api/data/v9.0/systemforms?%24select=formid%2Cname%2Cobjecttypecode%2Ctype%2Cformxml&%24filter=objecttypecode+eq+%27wti_equipmentselection%27 

DOES return the forms...

![image](https://user-images.githubusercontent.com/72568950/214371461-d39ab482-59c8-4f58-83f5-e29f6ea80dec.png)

**Comment by alexeisenhart** [comment]
`Library name="gp_/js/dosm_DependentOptionSet.js` This was a web resource that I created while first evaluating the tool, and then I deleted the resource. I forgot to remove it from the form -- IDK why make.powerapps.com let me delete the resource if it was used. I just removed that resource from the form, refreshed DOSM manager, and the form now shows up in the list. 

Thank you for your help!

**Comment by GuidoPreite** [comment]
thanks for reporting your solution. I close the issue.
